var QUESTION_BANK = {
    maths: [
        {q:"What is √144?",o:["10","11","12","13"],a:"12"},
        {q:"If x+5=12, find x",o:["5","6","7","17"],a:"7"},
        {q:"25% of 200?",o:["25","50","75","100"],a:"50"},
        {q:"Sum of angles in triangle?",o:["90°","180°","270°","360°"],a:"180°"},
        {q:"Area 10×5 rectangle?",o:["15","30","50","100"],a:"50"},
        {q:"15% of 300?",o:["35","40","45","50"],a:"45"},
        {q:"√169?",o:["11","12","13","14"],a:"13"},
        {q:"2³ = ?",o:["6","8","9","12"],a:"8"},
        {q:"5! = ?",o:["25","60","100","120"],a:"120"},
        {q:"LCM of 4 and 6?",o:["2","4","12","24"],a:"12"},
        {q:"HCF of 12 and 18?",o:["2","4","6","12"],a:"6"},
        {q:"Average of 10,20,30,40?",o:["20","25","30","35"],a:"25"},
        {q:"Next prime after 7?",o:["9","10","11","13"],a:"11"},
        {q:"100÷4×5?",o:["20","100","125","500"],a:"125"},
        {q:"Triangle 3,4,5 is?",o:["Equilateral","Isosceles","Right-angled","Obtuse"],a:"Right-angled"}
    ],
    science: [
        {q:"Water formula?",o:["H2O","CO2","NaCl","O2"],a:"H2O"},
        {q:"Speed of light?",o:["3×10⁶","3×10⁷","3×10⁸","3×10⁹"],a:"3×10⁸"},
        {q:"SI unit of force?",o:["Joule","Newton","Watt","Pascal"],a:"Newton"},
        {q:"Red planet?",o:["Venus","Mars","Jupiter","Saturn"],a:"Mars"},
        {q:"Atomic number of Carbon?",o:["4","6","8","12"],a:"6"},
        {q:"Plants absorb which gas?",o:["O2","N2","CO2","H2"],a:"CO2"},
        {q:"Powerhouse of cell?",o:["Nucleus","Ribosome","Mitochondria","Golgi"],a:"Mitochondria"},
        {q:"Symbol for Gold?",o:["Go","Gd","Au","Ag"],a:"Au"},
        {q:"Heart pumps?",o:["Air","Blood","Food","Water"],a:"Blood"},
        {q:"Unit of current?",o:["Volt","Watt","Ampere","Ohm"],a:"Ampere"},
        {q:"Newton's 1st law?",o:["Inertia","Acceleration","Action-Reaction","Conservation"],a:"Inertia"},
        {q:"Vitamin from sun?",o:["A","B","C","D"],a:"D"},
        {q:"pH of water?",o:["0","7","10","14"],a:"7"},
        {q:"Kinetic energy formula?",o:["½mv","½mv²","mv²","mgh"],a:"½mv²"},
        {q:"Myopia lens?",o:["Convex","Concave","Bifocal","Cylindrical"],a:"Concave"}
    ],
    english: [
        {q:"Correct spelling?",o:["Accomadation","Accommodation","Acommodation","Accomadation"],a:"Accommodation"},
        {q:"Synonym of Happy?",o:["Sad","Joyful","Angry","Tired"],a:"Joyful"},
        {q:"Antonym of Ancient?",o:["Old","Historic","Modern","Classic"],a:"Modern"},
        {q:"Article before honest?",o:["A","An","The","No"],a:"An"},
        {q:"Plural of Child?",o:["Childs","Children","Childrens","Childes"],a:"Children"},
        {q:"Noun in 'She reads'?",o:["She","reads","books","She reads"],a:"books"},
        {q:"Preposition: cat ___ table",o:["in","on","at","by"],a:"on"},
        {q:"Past tense of Write?",o:["Wrote","Written","Writing","Writed"],a:"Wrote"},
        {q:"Personification example?",o:["Simile","Metaphor","Personification","Hyperbole"],a:"Personification"},
        {q:"Who wrote Romeo?",o:["Dickens","Shakespeare","Austen","Twain"],a:"Shakespeare"},
        {q:"Command sentence type?",o:["Declarative","Interrogative","Imperative","Exclamatory"],a:"Imperative"},
        {q:"Conjunction: I can swim ___ fly",o:["and","but","or","so"],a:"but"},
        {q:"Feminine of Lion?",o:["Lioness","Liona","Liones","Lionesss"],a:"Lioness"},
        {q:"Type of 'happiness'?",o:["Proper","Common","Abstract","Collective"],a:"Abstract"},
        {q:"'Piece of cake' means?",o:["Food","Something easy","Birthday","Insult"],a:"Something easy"}
    ],
    hindi: [
        {q:"पुस्तक का बहुवचन?",o:["पुस्तकें","पुस्तकों","पुस्तकिया","पुस्तकोंकी"],a:"पुस्तकें"},
        {q:"गाय की स्त्रीलिंग?",o:["गायन","गायें","गायी","गाई"],a:"गायी"},
        {q:"माता का पुलिंग?",o:["पिता","माता","पुत्र","बालक"],a:"पिता"},
        {q:"शीघ्र का विलोम?",o:["तेज","धीरे","जल्दी","त्वरित"],a:"धीरे"},
        {q:"विशेषण शब्द?",o:["दौड़","तेज","विद्यालय","पढ़ाई"],a:"तेज"},
        {q:"सुधि का अर्थ?",o:["बुराई","भलाई","ज्ञान","अज्ञान"],a:"भलाई"},
        {q:"पत्र का अर्थ?",o:["निबंध","पत्र","नाटक","कहानी"],a:"पत्र"},
        {q:"तुम का सम्मान रूप?",o:["तू","आप","यह","वह"],a:"आप"},
        {q:"कवि की स्त्रीलिंग?",o:["कवयिनी","कवि","कवयित्री","कवियास"],a:"कवयिनी"},
        {q:"हार का विलोम?",o:["जीत","खेल","हारजीत","युद्ध"],a:"जीत"},
        {q:"संयुक्त वर्ण?",o:["क्क","क्र","द्म","स्व"],a:"क्र"},
        {q:"हाथ मलना मुहावरा?",o:["हाथ धोना","तैयारी","निराश","खुश"],a:"तैयारी"},
        {q:"पूर्णविराम क्या है?",o:["अल्पविराम","पूर्णविराम","प्रश्नवाचक","सभी"],a:"पूर्णविराम"},
        {q:"अत्याधिक संधि?",o:["अति+आधिक","अत्य+आधिक","अत्याधि+क","नहीं"],a:"अत्य+आधिक"},
        {q:"राम ने देखा वाक्य प्रकार?",o:["विधि","संदेह","निश्चय","प्रश्न"],a:"निश्चय"}
    ],
    sst: [
        {q:"First President of India?",o:["Nehru","Rajendra Prasad","Gandhi","Ambedkar"],a:"Rajendra Prasad"},
        {q:"Capital of India?",o:["Mumbai","Kolkata","New Delhi","Chennai"],a:"New Delhi"},
        {q:"Flag designer?",o:["Nehru","Gandhi","Venkaiah","Ambedkar"],a:"Venkaiah"},
        {q:"Ganga of South?",o:["Krishna","Kaveri","Godavari","Narmada"],a:"Godavari"},
        {q:"Quit India Year?",o:["1940","1941","1942","1943"],a:"1942"},
        {q:"Discovery of India author?",o:["Gandhi","Nehru","Tagore","Ambedkar"],a:"Nehru"},
        {q:"Largest state by area?",o:["MP","Maharashtra","Rajasthan","UP"],a:"Rajasthan"},
        {q:"National animal?",o:["Lion","Tiger","Elephant","Peacock"],a:"Tiger"},
        {q:"Father of Nation?",o:["Nehru","Gandhi","Bose","Ambedkar"],a:"Gandhi"},
        {q:"National Song?",o:["Jana Gana Mana","Vande Mataram","Saare Jahan","Hum Dekhenge"],a:"Vande Mataram"},
        {q:"Constitution adopted?",o:["26 Jan 1950","15 Aug 1947","26 Nov 1949","2 Oct 1947"],a:"26 Nov 1949"},
        {q:"States in India?",o:["26","28","30","32"],a:"28"},
        {q:"Right to Equality?",o:["Art 14","Art 19","Art 21","Art 32"],a:"Art 14"},
        {q:"First Parliament?",o:["1946","1947","1948","1949"],a:"1947"},
        {q:"India currency?",o:["Dollar","Rupee","Yen","Euro"],a:"Rupee"}
    ],
    mixed: []
};
for(var k in QUESTION_BANK){if(k!=='mixed')QUESTION_BANK.mixed=QUESTION_BANK.mixed.concat(QUESTION_BANK[k])}
function shuffle(a){for(var i=a.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1));var t=a[i];a[i]=a[j];a[j]=t}return a}
function shuffleQ(q){return{q:q.q,o:shuffle(q.o.slice()),a:q.a}}